import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navar";

export const metadata: Metadata = {
  title: "Stor for all",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}</body>
    </html>
  );
}
