import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navar";
import Layout from "@/components/layout";
import { ShoppingCartContextProvider } from "@/context/ShoppingCartContext";


export const metadata: Metadata = {
  title: "Stor for all",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
       <ShoppingCartContextProvider>
         <Layout>{children}</Layout>
       </ShoppingCartContextProvider>
      </body>
    </html>
  );
}
